# Generated by Django 4.1.3 on 2022-12-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkrealty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
