# Generated by Django 4.1.3 on 2022-12-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkrealty', '0002_realty_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], default='Sale', max_length=10),
        ),
    ]
