# Generated by Django 4.1.3 on 2022-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkrealty', '0003_realty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Sold', 'SOLD'), ('Rented', 'RENTED')], default='Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='realty',
            name='type',
            field=models.CharField(choices=[('Sale', 'SALE'), ('Rent', 'RENT')], default='Sale', max_length=10),
        ),
    ]
